server:
  config:
    persistence:
      default:
        driver: "sql"

        sql:
          driver: "mysql"
          host: temporal-db.cfoehvo1ip9p.us-west-2.rds.amazonaws.com
          port: 3306
          database: temporal
          user: admin
          password: TEST
          maxConns: 20
          maxConnLifetime: "1h"

      visibility:
        driver: "sql"

        sql:
          driver: "mysql"
          host: temporal-db.cfoehvo1ip9p.us-west-2.rds.amazonaws.com
          port: 3306
          database: temporal_visibility
          user: admin
          password: TEST
          maxConns: 20
          maxConnLifetime: "1h"

cassandra:
  enabled: false

mysql:
  enabled: true

postgresql:
  enabled: false

schema:
  setup:
    enabled: false
  update:
    enabled: false
