server:
  config:
    persistence:
      default:
        driver: "sql"

        sql:
          driver: "postgres"
          host: temporal.cfoehvo1ip9p.us-west-2.rds.amazonaws.com
          port: 5432
          database: temporal
          user: postgres
          password: TEST
          maxConns: 20
          maxConnLifetime: "1h"

      visibility:
        driver: "sql"

        sql:
          driver: "postgres"
          host: temporal.cfoehvo1ip9p.us-west-2.rds.amazonaws.com
          port: 5432
          database: temporal_visibility
          user: postgres
          password: TEST
          maxConns: 20
          maxConnLifetime: "1h"

cassandra:
  enabled: false

mysql:
  enabled: false

postgresql:
  enabled: true

schema:
  setup:
    enabled: false
  update:
    enabled: false
