---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: temporal-ui
spec:
  selector:
    matchLabels:
      app: temporal-ui
  replicas: 2
  template:
    metadata:
      labels:
        app: temporal-ui
    spec:
      containers:
        - name: temporal-ui
          image: temporalio/ui
#          command: [ "/bin/bash", "-c", "--" ]
#          args: [ "while true; do sleep 30; done;" ]
          ports:
            - name: ui
              containerPort: 8080
          env:
            - name: TEMPORAL_ADDRESS
              value: temporal-frontend:8233
            - name: TEMPORAL_CORS_ORIGINS
              value: http://localhost:3000
            - name: TEMPORAL_UI_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-ui
  namespace: dev
spec:
  selector:
    app: temporal-ui
  ports:
    - name: ui
      port: 8080
      targetPort: 8080
  type: NodePort
